# Generated by Django 5.2.6 on 2025-09-15 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_team_shift_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancemark',
            index=models.Index(fields=['session', 'student'], name='attendance__session_0a3f48_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemark',
            index=models.Index(fields=['student'], name='attendance__student_b7ebe3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['section', 'date'], name='attendance__section_0cfbf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('section', 'date'), name='unique_section_date'),
        ),
    ]
